PERSON_LEVEL_ATTRS = {
    "ABWDSTI": "ABAWD status",
    "AGEI": "Age",
    "CTZNI": "Citizenship status",
    "DISI": "Person-level disability indicator",
    "DPCOSTI": "Reported dependent care cost",
    "EMPRGI": "SNAP Employment and Training program status",
    "EMPSTAI": "Employment status—type",
    "EMPSTBI": "Employment status—amount",
    "FSAFLI": "SNAP case affiliation",
    "FSUNI": "Position of head of SNAP unit",
    "NDISCAI": "Adult age 18–49 without disabilities in childless unit status",
    "RACETHI": "Race/ethnicity",
    "RELI": "Relationship to head of household",
    "SEXI": "Sex",
    "WORKI": "Person-level working indicator",
    "WRKREGI": "Work registration status",
    "YRSEDI": "Highest educational level completed",
}

REL = {
    1: "head of the household",
    2: "the spouse to the head of the household",
    3: "the parent to the head of the household",
    4: "the daughter, stepdaughter, son, or stepson to the head of the household",
    5: "a relative (brother, sister, niece, nephew, grandchild, great-grandchild, cousin) to the head of the household",
    6: "a foster child",
    7: "not related to the head of the household",
}

# SNAP CASE AFFILIATION 1-16
FSAFIL = {
    1: "is eligible for this SNAP case under review and entitled to receive benefits",
    # added by Mathematica for SNAP-CAP units
    2: "is eligible for SNAP in another SNAP unit, not currently under review",
    # no code 3 included
    4: "is SNAP ineligible. They are a noncitizen and not participating in State-funded SNAP",
    5: "is SNAP ineligible. They are not paying/cooperating with child support agency",
    6: "is SNAP ineligible. They are on strike",
    7: "is SNAP ineligible. They are a student",
    8: "is SNAP ineligible. They were disqualified for a program violation",
    9: "is SNAP ineligible due to disqualification or failure to meet work requirements (work registration, E&T, acceptance of employment, employment status/job availability, voluntary quit/reducing work effort, workfare/comparable workfare)",
    10: "is SNAP ineligible due to able-bodied adult without dependents (ABAWD) and their time limit exhausted and they failed to meet ABAWD work requirements (to work at least 20 hours per week, to participate in at least 20 hours per week in qualifying educational training activities, or to participate in workfare)",
    11: "is SNAP ineligible because they are a fleeing felon or a parole and probation violator",
    # no code for 12 included
    13: "is SNAP ineligible because they are a convicted drug felon",
    14: "is SNAP ineligible because their Social Security Number was disqualified",
    15: "is SNAP ineligible because they are a SSI recipient in California",
    16: "is SNAP ineligible because they are a prisoner in detention center",
    17: "is SNAP ineligible because they are in foster care",
    18: "is SNAP ineligible because they are a noncitizen and participating in State-funded SNAP",
    19: "is SNAP ineligible. They are an individual in the home but not part of SNAP household",
    99: "has an unknown SNAP eligibility status",
}


CTZN = {
    1: "a US-born citizen",
    2: "a naturalized citizen",
    3: "a legal permanent resident with 40 quarters of work, military service, five years legal U.S. residency, disability, or under age 18",
    5: "a person admitted as refugee, granted asylum, or given stay of deportation",
    6: "an other eligible noncitizen",
    7: "a noncitizen legally in U.S. who does not meet one of the above codes and is not receiving SNAP benefits but whose income and resources must be considered in determining benefits",
    8: "an other ineligible legal noncitizen (for example, visitor, tourist, student, diplomat)",
    9: "an undocumented noncitizen",
    10: "a noncitizen, status unknown",
}

SEX = {1: "male", 2: "female"}

DIS = {0: "have a disability", 1: "do not have a disability"}

RACETH = {
    1: "Their racial/ethnic information is not available because application was not found",
    2: "Their racial/ethnic information was not recorded on application",
    3: "They are an American Indian or Alaska Native",
    4: "They are Asian",
    5: "They are Black or African American",
    6: "They are Native Hawaiian or other Pacific Islander",
    7: "They are White",
    8: "They are American Indian or Alaska Native and White",
    9: "They are biracial; They are Asian and White",
    10: "They are biracial; They are Black or African American and White",
    11: "They are biracial; They are American Indian or Alaska Native and Black or African American",
    # = Respondent reported more than one race and does not fit into above categories (codes 8 through 11)
    12: "They reported more than one race and do not fit into a category",
    13: "They are biracial; They are Hispanic or Latino and American Indian or Alaska Native",
    14: "They are biracial; They are Hispanic or Latino and Asian",
    15: "They are biracial; They are Hispanic or Latino and Black or African American",
    16: "They are biracial; They are Hispanic or Latino and Native Hawaiian or other Pacific Islander",
    17: "They are biracial; They are Hispanic or Latino and White",
    18: "They are multiracial; They are Hispanic or Latino and American Indian or Alaska Native and White",
    19: "They are multiracial; They are Hispanic or Latino and Asian and White",
    20: "They are multiracial; They are Hispanic or Latino and Black or African American and White",
    21: "They are multiracial; They are Hispanic or Latino and American Indian or Alaska Native and Black or African American",
    # = (Hispanic or Latino) and respondent reported more than one race and does not fit into above categories (codes 18 through 21)
    22: "They are Hispanic or Latino, and reported more than one race and doesn't fit into a category",
}

YRSED = {
    0: "They did not complete any schooling",
    1: "Their highest education attained is through grade 1",
    2: "Their highest education attained is through grade 2",
    3: "Their highest education attained is through grade 3",
    4: "Their highest education attained is through grade 4",
    5: "Their highest education attained is through grade 5",
    6: "Their highest education attained is through grade 6",
    7: "Their highest education attained is through grade 7",
    8: "Their highest education attained is through grade 8",
    9: "Their highest education attained is through grade 9",
    10: "Their highest education attained is through grade 10",
    11: "Their highest education attained is through grade 11",
    12: "They are a high school graduate or have their GED",
    13: "They have a postsecondary education or have a technical education or started but did not finish college",
    14: "They are a college graduate or have a postgraduate degree",
}

WORK = {0: "not employed", 1: "working"}

EMPSTA = {
    1: "and not looking for work",
    2: "and looking for work",
    3: "as active-duty military",
    4: "as a migrant farm laborer",
    5: "as a nonmigrant farm laborer",
    6: "as a self-employed farmer",
    7: "as self-employed that is not farming",
    8: "and employed by someone else",
}

WRKREG_2021 = {
    1: "Work registrant",
    2: "Federal exemption, physically or mentally unfit for employment",
    3: "Federal exemption, care of a child under 6 or an incapacitated person",
    4: "Federal exemption, working and/or earning the equivalent of 30 hours per week",
    5: "Federal exemption, other",
}


AGENCY = {
    1: "Information not reported",
    2: "Incomplete or incorrect information provided; agency not required to verify",
    3: "Information withheld by client (case referred for Intentional Program Violation [IPV] investigation",
    4: "Incorrect information provided by client (case referred for IPV investigation)",
    # no codes provided for 5 and 6
    7: "Inaccurate information reported by collateral contact",
    8: "Acted on incorrect Federal computer match information not requiring verification (such variance is excluded from error determination but must be recorded)",
    # no code provided for 9
    10: "Policy incorrectly applied",
    # no code provided for 11
    12: "Reported information disregarded or not applied",
    # no code provided for 13
    14: "Agency failed to follow up on inconsistent or incomplete information",
    15: "Agency failed to follow up on impending changes",
    16: "Agency failed to verify required information",
    17: "Computer programming error",
    18: "Data entry and/or coding error",
    19: "Mass change (error due to problem with computer- generated mass change)",
    20: "Arithmetic computation error",
    21: "Computer user error",
    99: "Other",
}

DISCOVERY = {
    1: "Variance clearly identified from case record (documentation not from an automated match)",
    2: "Variance clearly identified from case record (documentation from an automated match)",
    3: "Variance discovered from recipient interview",
    4: "Employer (present or former)",
    5: "Financial institution, insurance company, or other business",
    6: "Landlord",
    7: "Government agency or public records, not automated match",
    8: "Government agency or public records, automated match",
    9: "Other",
}

ERROR_FINDING = {2: "Overissuance", 3: "Underissuance", 4: "Ineligible"}

ELEMENT_VARIANCE = {
    111: "Student status",
    130: "Citizenship and noncitizen status",
    140: "Residency",
    150: "Unit composition",
    151: "Recipient disqualification",
    160: "Employment and training programs",
    161: "Time-limited participation",
    162: "Work registration requirements",
    163: "Voluntary quit/reduced work effort",
    164: "Workfare and comparable workfare",
    165: "Employment status/job availability",
    166: "Acceptance of employment",
    170: "Social Security number",
    211: "Bank accounts or cash on hand",
    212: "Nonrecurring lump-sum payment",
    213: "Other liquid assets",
    221: "Real property",
    222: "Vehicles",
    224: "Other nonliquid resources",
    225: "Combined resources",
    311: "Wages and salaries",
    312: "Self-employment",
    314: "Other earned income",
    321: "Earned income deductions",
    323: "Dependent care deduction",
    331: "RSDI benefits",
    332: "Veterans' benefits",
    333: "SSI and/or State SSI supplement",
    334: "Unemployment compensation",
    335: "Workers' compensation",
    336: "Other government benefits",
    342: "Contributions",
    343: "Deemed income",
    344: "TANF, PA, or GA",
    345: "Educational grants/scholarships/loans",
    346: "Other unearned income",
    350: "Child support payments received from absent parent",
    361: "Standard deduction",
    363: "Shelter deduction",
    364: "Standard utility allowance",
    365: "Medical expense deductions",
    366: "Child support payment deduction",
    371: "Combined gross income",
    372: "Combined net income",
    520: "Arithmetic computation",
    530: "Transitional benefits",
    560: "Reporting systems",
    810: "SNAP simplification project",
    820: "Demonstration projects",
}

NATURE_VARIANCE = {
    6: "Eligible person(s) excluded",
    7: "Ineligible person(s) included",
    12: "Eligible person(s) with no income, resources, or deductible expenses excluded",
    13: "Eligible person(s) with income excluded",
    14: "Eligible person(s) with resources excluded",
    15: "Eligible person(s) with deductible expenses excluded",
    16: "Newborn improperly excluded",
    20: "Incorrect resource limit applied",
    24: "Resource should have been excluded",
    28: "Incorrect income limit applied",
    29: "Exceeds prescribed limit",
    30: "Resource should have been included",
    32: "Failed to consider or incorrectly considered income of ineligible member",
    35: "Unreported source of income (do not use for change in employment status)",
    36: "Rounding used/not used or incorrectly applied",
    37: "All income from source known but not included",
    38: "More income received from this source than budgeted",
    39: "Employment status changed from unemployed to employed",
    40: "Employment status changed from employed to unemployed",
    41: "Change only in amount of earnings",
    42: "Conversion to monthly amount not used or incorrectly applied",
    43: "Averaging not used or incorrectly applied",
    44: "Less income received from this source than budgeted",
    45: "Cost of doing business not used or incorrectly applied",
    46: "Failed to consider/anticipate month with extra pay date",
    52: "Deduction that should have been included was not",
    53: "Deduction included that should not have been",
    54: "Incorrect standard used (not as a result of change in unit size or move)",
    64: "Incorrect amount used resulting from change in residence",
    65: "Incorrect standard used resulting from change in unit size",
    75: "Benefit/allotment/eligibility incorrectly computed",
    77: "Unit not entitled to transitional benefits",
    79: "Incorrect use of allotment tables",
    80: "Improper prorating of initial month's benefits",
    97: "Not required to be reported or acted upon based on time frames and reporting requirements for allotment differences below the error threshold",
    98: "Transcription or computation errors",
    99: "Other",
    111: "Child support payment(s) not considered or incorrectly applied for initial month(s) of eligibility",
    112: "Retained child support payment(s) not considered or incorrectly applied",
    120: "Variance/errors resulting from noncompliance with this means-tested public assistance program",
    123: "Incorrectly prorated",
    124: "Variances resulting from use of automatic Federal information exchange system",
    127: "Pass-through not considered or incorrectly applied",
    200: "Eligible noncitizen excluded",
    201: "Ineligible noncitizen included",
    301: "Unit improperly participating under retrospective budgeting",
    302: "Unit improperly participating under prospective budgeting",
    303: "Unit improperly participating under monthly reporting",
    304: "Unit improperly participating under quarterly reporting",
    305: "Unit improperly participating under semiannual reporting",
    306: "Unit improperly participating under change reporting",
    307: "Unit improperly participating under status reporting",
    308: "Unit improperly participating under 5 hour reporting",
    309: "Unit improperly participating in transitional benefits",
}

VARIANCE_VERIFICATION = {
    1: "From case record (verification not from an automated match)",
    2: "From case record (verification from an automated match)",
    3: "From information provided by recipient",
    4: "Employer (present or former)",
    5: "Financial institution, insurance company, or other business",
    6: "Landlord",
    7: "Government agency or public records, not automated match",
    8: "Government agency or public records, automated match",
    9: "Other",
}
